config/routes.rb
Soshop::Application.routes.draw do
  get 'pages/home'

  resources :products

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'pages#home'

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
end

app/models/delivery_method.rb
class DeliveryMethod < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  #belongs_to :delivery_method
  #belongs_to :payment_method
  belongs_to :product

  validates :user_id, presence: true
  validates :product_id, presence: true
  #validates :payment_method_id, presence: true
  #validates :delivery_method_id, presence: true
end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  belongs_to :user
  validates :user, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_attached_file :photo, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  validates :user_id, presence: true
  validates :title, presence: true
  validates :price, presence: true,
    numericality: { greater_than_or_equal_to: 0 }
  validates :stock, presence: true,
    numericality: { only_integer: true }
  validates_attachment_presence :photo
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :orders
  has_many :payment_methods
  has_many :delivery_methods
  has_many :addresses
  has_many :credit_cards

  def self.find_for_facebook_oauth(auth)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create( name: auth.extra.raw_info.name,
                          provider: auth.provider,
                          uid: auth.uid,
                          email: auth.info.email,
                          password: Devise.friendly_token[0,20]
      )
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @product_id = params[:product_id]
  end

  # GET /orders/1/edit
  def edit
    @product_id = @order.product.id
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user = current_user

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(
        :delivery_method_id,
        :payment_method_id,
        :product_id,
        :full_name,
        :email,
        :card_number,
        :security_code,
        :expiration_date
      )
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: :show
  before_filter :product_creator, only: [:edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.where(user_id: current_user.id)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :photo, :user_id, :stock)
    end

    def product_creator
      if @product.user != current_user
        err_msg = 'You cannot modify this product.'
        flash.now[:error] = err_msg
        respond_to do |format|
          format.html { redirect_to @product }
          format.json { render json: err_msg, status: :unprocessable_entity }
        end
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper

  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Please correct the following problems and try again")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, id: 'error_explanation') do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:div, options[:message], :class=>"alert alert-error") +
        content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Winkealo" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= analytics_init if Rails.env.production? %> <!-- GA.tracker -->
  </head>
  <body>

    <header>
      <nav role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><%= image_tag 'logo-winkealo.png', class: 'logo' %></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/"><%= t('home') %></a></li>
            <li><%= link_to t('products'), products_path %></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-user"></i>
                  <%= current_user.email %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to raw('<i class="icon-cog"></i> Profile'), edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to raw('<i class="icon-off"></i> Logout'), destroy_user_session_path, method: :delete %></li>
                </ul>
              </li><!-- /dropdown -->
            <% else %>
              <li><%= link_to t('login'), new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>

      <%= yield(:header) if content_for?(:header) %>
    </header>

    <article>
      <%= yield %>
    </article>

    <footer>
      <p><strong>Winkealo</strong> • Todos los Derechos Reservados &copy; <%= Time.now.year %></p>
    </footer>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/orders/_form.html.erb
<div class="">
  <%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

        <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :product_id, value: @product_id.to_s %>

    <div class="container-fluid">
    <div class="row-fluid">
      <div class="span8">
        <div class="well">
          <h4>Contact Information</h4>
          <div class="field">
            <%= f.label :full_name, 'Full Name' %><br>
            <%= f.text_field :full_name %>
          </div>
          <div class="field">
            <%= f.label :email, 'Email Address' %><br>
            <%= f.text_field :email %>
          </div>
        </div>

        <div class="well">
          <h4>Card Information</h4>
          <div class="field">
            <%= f.label :card_number, 'Card Number' %><br>
            <%= f.text_field :card_number %>
          </div>
          <div class="field">
            <%= f.label :security_code, 'Security Code' %><br>
            <%= f.text_field :security_code %>
          </div>
          <div class="field">
            <%= label_tag :card_month, "Card Expiration" %>
            <%= select_month nil, {add_month_numbers_true: true}, {name: nil, id: "card_month"}%>
            <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+10}, {name: nil, id: "card_year"}%>
          </div>
        </div>
      </div>
      <div class="span4">
        <div class="well">
          <h4>Payment Summary</h4>
          <div class="actions">
            <%= f.submit %>
          </div>
        </div>
      </div>
    </div></div>
  <% end %>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Delivery method</th>
      <th>Payment method</th>
      <th>Product</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user %></td>
        <td><%= order.delivery_method %></td>
        <td><%= order.payment_method %></td>
        <td><%= order.product %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order.attributes %>
</p>


<p>
  <strong>User:</strong>
  <%= @order.user.attributes %>
</p>

<!-- <p>
  <strong>Delivery method:</strong>
  <%#= @order.delivery_method %>
</p>

<p>
  <strong>Payment method:</strong>
  <%#= @order.payment_method %>
</p>
 -->
<p>
  <strong>Product:</strong>
  <%= @order.product.attributes %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/home.html.erb
<% content_for :title do %>
  Winkealo | resgistra - comparte - vende
<% end %>

<% content_for :header do %>
  <section class="banner">
    <h1>Comenzar a vender online no es fácil, nosotros lo simplificamos</h1>
    <h2>Publica con nosotros _________________ y comienza a vender ___________ </h2>
  </section>
<% end %>

<div class="wrapper">
  <article class="column-aside">
    <section>
      <h1>Que es Winkealo?</h1>
      <p>Es una plataforma de comercio electónico que utiliza las redes sociales para multiplicar tu poder de venta.</p>
      <ul>
        <li>Alcanza a miles de usuarios.</li>
        <li>Reduce costo y dificultad para vender online.</li>
        <li>Lleva tu tienda a la nube con nosotros.</li>
        <li>Aprovecha el poder de las ventas virales.</li>
      </ul>

      <button><%= t('login') %></button>
    </section>
    <aside>
      <%= image_tag 'cart.jpg' %>
    </aside>
  </article>

  <article class="three-sections">
    <section>
      <span class="fa-stack fa-5x icons">
        <i class="fa fa-circle-thin fa-stack-2x"></i>
        <i class="fa fa-laptop fa-stack-1x"></i>
      </span>
      <h1>Registra</h1>
      <p>Regístrate tus productos con nosotros gratis y comienza a vender en segundos.</p>
    </section>

    <section>
      <span class="fa-stack fa-5x icons">
        <i class="fa fa-circle-thin fa-stack-2x"></i>
        <i class="fa fa-share-alt fa-stack-1x"></i>
      </span>
      <h1>Comparte</h1>
      <p>Comparte tus productos directamente a tus fans y seguidores. Ellos estarán a solo dos clicks de distancia de comprarte.</p>
    </section>

    <section>
      <span class="fa-stack fa-5x icons">
        <i class="fa fa-circle-thin fa-stack-2x"></i>
        <i class="fa fa-shopping-cart fa-stack-1x"></i>
      </span>
      <h1>Vende</h1>
      <p>Relájate y mira como tus ventas aumentan. Nosotros manejamos el resto, desde el pago hasta el envío.</p>
    </section>
  </article>

  <article class="one-column">
    <form class="form-horizontal" role="form">
      <legend>Subscríbete</legend>

      <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Nombre</label>
        <div class="col-sm-5">
          <input type="text" class="form-control" id="nombre" placeholder="Pon tu nombre">
        </div>
      </div>

      <div class="form-group">
        <label for="inputPassword3" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-5">
          <input type="email" class="form-control" id="email" placeholder="Pon tu email">
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Enviar</button>
        </div>
      </div>
    </form>
  </article>
</div>

app/views/products/_form.html.erb
<%= form_for @product, html: { class: 'form-horizontal', multipart: true } do |f| %>
  <%= error_messages_for(@product) %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :stock, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :stock, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :photo, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :photo, :class => 'file_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:stock) %></th>
      <!-- <th><%#= model_class.human_attribute_name(:photo) %></th> -->
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.title, product_path(product) %></td>
        <td><%= product.description %></td>
        <td><%= number_to_currency product.price %></td>
        <td><%= product.stock %></td>
        <!-- <td><%#= product.photo %></td> -->
        <td><%=l product.created_at, format: :short %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<% content_for :title do "#{@product.title} | Soshop" end %>

<%- model_class = Product -%>

<div class="hero-unit">
  <h1><%= @product.title %></h1>
  <p><%= @product.description %></p>
  <p></p>
  <p><%= image_tag @product.photo.url %></p>
  <p>
    <%= link_to t('.buy_now', :default => t("helpers.links.buy_now")),
      new_order_path(product_id: @product.id), :class => 'btn btn-primary btn-large', id: 'buy_now'  %>
      <%= number_to_currency(@product.price) %>
  </p>
  <% if current_user && current_user == @product.user %>
    <p><%= @product.stock %> in stock.</p>
  <% end %>
</div>

<% if current_user && current_user == @product.user %>
  <div class="form-actions">
    <a  href="https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>"
        target="_blank" class="btn btn-success">
      share on facebook
    </a>
    <%= link_to t('.back', :default => t("helpers.links.back")),
                products_path, :class => 'btn'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_product_path(@product), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                product_path(@product),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  </div>
<% end %>